Repository cp-geeks-adgitm/Hacktoberfest, pull requests merged in 2022-10, with the labels that each got.

#171 BusRoutes_C++.cpp
  Leetcode-Solutions/Graph/Biparte.cpp
  Leetcode-Solutions/Graph/CourseI.cpp
  Leetcode-Solutions/Graph/RottenOranges.cpp
  Leetcode-Solutions/Graph/Routes.cpp
  Leetcode-Solutions/Graph/Sliding.cpp
  Leetcode-Solutions/Graph/ladder.cpp
  Leetcode-Solutions/Strings/subsequence.cpp
Labels: hacktoberfest-accepted

#156 Create phone directory.cpp
  Data-structures/List/phone directory.cpp
Labels: hacktoberfest-accepted

#157 Create Threaded binary tree example.cpp
  Data-structures/Threaded binary tree example.cpp
Labels: hacktoberfest-accepted

#158 Added BST, Stack, Doubly Link List
  Data-structures/List/doublyll.cpp
  Data-structures/Stack/stack_operations.cpp
  Data-structures/bst_operations.cpp
  README.md
Labels: hacktoberfest-accepted

#160 Update Detect-Captital_C++.cpp
  Leetcode-Solutions/Strings/Detect-Captital_C++.cpp
Labels: hacktoberfest-accepted

#234 Create balanced_parenthesis_stack.cpp
  Data-structures/Stack/balanced_parenthesis_stack.cpp
Labels: hacktoberfest-accepted

#168 Create Codeforces_1421A_XORwice.cpp
  Bitwise-Hacks/Codeforces_1421A_XORwice.cpp
Labels: hacktoberfest-accepted

#144 Create mergeSort.c
  Algorithms/mergeSort.c
Labels: hacktoberfest-accepted

#120 Bit tricks added.
  Bit-tricks/Addition-without-arithmetic_C++.cpp
  Bit-tricks/Odd-occuring_C++.cpp
  Bit-tricks/Swapping-two-no_C++.cpp
Labels: hacktoberfest-accepted

#58 Leetcode Solutions of LinkedList
  Data-structures/TRIE/StreamOfCharactersLeetCode_Java.java
  Data-structures/TRIE/Tclient_Java.java
  Data-structures/TRIE/TrieCode_Java.java
  Leetcode-Solutions/LinkedList/CopyListWithRandomPointers1_Java.java
  Leetcode-Solutions/LinkedList/CopyListWithRandomPointers2_Java.java
  Leetcode-Solutions/LinkedList/FlattenMultilevelLinklist.java
  Leetcode-Solutions/LinkedList/IntersectionOfTwoLinkedLists.java
  Leetcode-Solutions/LinkedList/LRUCache.java
  Leetcode-Solutions/LinkedList/MergeKSortedLists_Java.java
  Leetcode-Solutions/LinkedList/OddEvenLinkedLists_Java.java
  Leetcode-Solutions/LinkedList/RemoveDuplicatesFromSortedList_Java.java
  Leetcode-Solutions/LinkedList/RemoveNthNodeFromEndOfList_Java.java
  Leetcode-Solutions/LinkedList/ReorderList_Java.java
  Leetcode-Solutions/LinkedList/ReorderORfold.java
  Leetcode-Solutions/LinkedList/ReverseLinkedList2.java
  Leetcode-Solutions/LinkedList/ReverseNodesInK-Groups_Java.java
  Leetcode-Solutions/LinkedList/RotateLinkedLists.java
  Leetcode-Solutions/Strings/split-array-into-fibonacci-sequence_java.java
Labels: hacktoberfest-accepted

#243 LEETCODE longest_palindromic_substring
  Leetcode-Solutions/Strings/longest_palindromic_substring.py
Labels: hacktoberfest-accepted

#245 LEETCODE find_first_and_last_position_of_element_in_sorted_array
  Leetcode-Solutions/Arrays/find_first_and_last_position_of_element_in_sorted_array.py
Labels: hacktoberfest-accepted

#246 LEETCODE climbing_stairs
  Leetcode-Solutions/DP/climbing_stairs.py
Labels: hacktoberfest-accepted

#253 added Implementation of stack using two queues
  Data-structures/Stack/implementation_of_stack_using_two_queues.cpp
  Leetcode-Solutions/Linked-List/palindrome-linked-list.cpp
Labels: hacktoberfest-accepted

#263 add code for majority element in python
  Leetcode-Solutions/Arrays/majority_element.py
Labels: hacktoberfest-accepted, hacktoberfest

#262 kadane's algo to find max sum of sub array in o(n)
  Algorithms/kadane's.py
Labels: hacktoberfest-accepted, hacktoberfest

#281 Translated cpp code of DSA course by William Fiset
  Willam fiset DSA c++ translated code/Arrays/Array.cpp
  Willam fiset DSA c++ translated code/Arrays/GenericArray.cpp
  Willam fiset DSA c++ translated code/Balanced Binary Search Tree/AVL Tree/AvlTreeRecursive.cpp
  Willam fiset DSA c++ translated code/Binary Search Tree/bst.cpp
  Willam fiset DSA c++ translated code/Fenwick Tree/FenwickTreeRangeQueryPointUpdate.cpp
  Willam fiset DSA c++ translated code/Fenwick Tree/FenwickTreeRangeUpdatePointQuery.cpp
  Willam fiset DSA c++ translated code/Hash Table/HashTableSeperateChaining.cpp
  Willam fiset DSA c++ translated code/Hash Table/OpenAdressingDoubleHashing.cpp
  Willam fiset DSA c++ translated code/Hash Table/OpenAdressingLinearProbing.cpp
  Willam fiset DSA c++ translated code/Hash Table/OpenAdressingQuadraticProbing.cpp
  Willam fiset DSA c++ translated code/Linked List/Doubly_Linked_list.cpp
  Willam fiset DSA c++ translated code/Linked List/Single_Linked_List.cpp
  Willam fiset DSA c++ translated code/Priority Queues/max_heap.cpp
  Willam fiset DSA c++ translated code/Priority Queues/max_priority_queue.cpp
  Willam fiset DSA c++ translated code/Priority Queues/min_index_priority_queue.cpp
  Willam fiset DSA c++ translated code/Priority Queues/min_priority_queue.cpp
  Willam fiset DSA c++ translated code/Priority Queues/min_priority_stack.cpp
  Willam fiset DSA c++ translated code/Queues & Deques/ArrayQueue.cpp
  Willam fiset DSA c++ translated code/Queues & Deques/Dequeue.cpp
  Willam fiset DSA c++ translated code/Queues & Deques/SingleLinkedListQueue.cpp
  Willam fiset DSA c++ translated code/Stack/ArrayStack.cpp
  Willam fiset DSA c++ translated code/Stack/SingleLinkedListStack.cpp
  Willam fiset DSA c++ translated code/Suffix Array/SuffixArrayFast.cpp
  Willam fiset DSA c++ translated code/Suffix Array/SuffixArraySlow.cpp
  Willam fiset DSA c++ translated code/Suffix Array/SuffixArraymed.cpp
  Willam fiset DSA c++ translated code/Tree/tree.cpp
  Willam fiset DSA c++ translated code/Union find/dsu.cpp
  Willam fiset DSA c++ translated code/readme.txt
Labels: hacktoberfest-accepted, hacktoberfest

#285 Trappin rain water leetcode solution
  Leetcode-Solutions/Arrays/TrappingRainwater.java
  README.md
Labels: hacktoberfest-accepted, hacktoberfest

#283 LEETCODE min_time_to_make_rope_colorful
  Leetcode-Solutions/Arrays/minimum-time-to-make-rope-colorful.py
Labels: hacktoberfest-accepted, hacktoberfest

#284 LEETCODE number-of-dice-rolls-with-target-sum
  Leetcode-Solutions/DP/number-of-dice-rolls-with-target-sum.py
Labels: hacktoberfest-accepted, hacktoberfest

#275 Subtree Queries CSES
  CSES-Solutions/Subtree Queries.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#272 Company Queries 2 CSES
  CSES-Solutions/Company Queries II.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#270 Tree Distances 2 CSES
  CSES-Solutions/Tree Distances II.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#269 Tree Distances 1
  CSES-Solutions/Tree Distances I
Labels: hacktoberfest-accepted, hacktoberfest

#268 Tree Diameter CSES
  CSES-Solutions/TreeDiameter.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#267 Subordinates CSES
  CSES-Solutions/Subordinates.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#280 Create ArrayOperations(MenuDrivenProgram)
  Data-structures/Arrays/ArrayOperations.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#261 Ltime112b-Incadd.cpp
  Contest/Codechef/Codechef-Sep-Lunchtime-Div2/Ltime112b-Incadd
Labels: hacktoberfest-accepted, hacktoberfest

#297 Bubble Sort using Recursion.cpp
  Algorithms/Sorting/Bubble Sort using Recursion.cpp
Labels: hacktoberfest

#299 anuj [TrappingRainWater]
  Algorithms/Dynamic Programming/TrappingRainWater.java
Labels: hacktoberfest-accepted, hacktoberfest
